### ISSUE TITLE
Support for column aliases

### ISSUE THREAD

**Issue by illuminoir** [squashql/squashql#186]
Currently, squashQL doesn't support column aliases. Here is an example of a query that causes errors :

```
SELECT id
FROM   (SELECT p.id,
               s.id
        FROM   recommendation rec
               JOIN product p
                 ON rec.product_id = p.id
               JOIN store s
                 ON rec.store_id = s.id) 
```

Here, the subquery queries for two different columns named `id` which causes an ambiguity error. 

Ideally, we would like to be able to generate the following query:

```
SELECT product_id
FROM   (SELECT p.id AS product_id,
               s.id AS store_id
        FROM   recommendation rec
               JOIN product p
                 ON rec.product_id = p.id
               JOIN store s
                 ON rec.store_id = s.id) 
```

**Comment by paulbares** [comment]
There is some issue with Spark when using grouping: https://issues.apache.org/jira/browse/SPARK-43851
