### ISSUE TITLE
Missing custom Jackson config bean

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#192]
In this recent PR #185, `String` have been replaced by `Field` in the `QueryDto`. So that Jackson knows how to handle this new class, the `ObjectMapper` configuration has been updated in the class `JacksonUtil` as follows:

```
public static final ObjectMapper OBJECT_MAPPER;

  static {
    OBJECT_MAPPER = new ObjectMapper();
    var simpleModule = new SimpleModule();
    simpleModule.addKeyDeserializer(Field.class, new QueryDto.KeyFieldDeserializer());
    simpleModule.addKeySerializer(Field.class, new QueryDto.KeyFieldSerializer());
    OBJECT_MAPPER.registerModule(simpleModule);
  }
```

This new configuration is taken into account by the SquashQL Rest Controller in the tests thanks to this bean, in the class `SquashQLApplication`: 
```
@Bean
  public MappingJackson2HttpMessageConverter jackson2HttpMessageConverter() {
    return new MappingJackson2HttpMessageConverter(JacksonUtil.OBJECT_MAPPER);
  }
```

The problem is that this **new bean is not created by SquashQL** outside tests. In addition to the `QueryController`, SquashQL should provide a configuration class with this new bean. Without this, users of `squashql-server` module will get a 415 http error when querying the rest controller, as jackson is unable to deserialize requests.

**Comment by paulbares** [comment]
Hi @jacques-charnay, you are right, we can provide a "default" config class. Do you want to create it and create a PR ? That would be very helpful.
