### ISSUE TITLE
Replace "any" types by "Field" in conditions

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#195]
As much as possible, the `any` type should be avoided in the SquashQL API.:
```
export function eq(value: any): Condition {
  return new SingleValueCondition(ConditionType.EQ, value)
}

export function neq(value: any): Condition {
  return new SingleValueCondition(ConditionType.NEQ, value)
}

export function lt(value: any): Condition {
  return new SingleValueCondition(ConditionType.LT, value)
}

export function le(value: any): Condition {
  return new SingleValueCondition(ConditionType.LE, value)
}

export function gt(value: any): Condition {
  return new SingleValueCondition(ConditionType.GT, value)
}

export function ge(value: any): Condition {
  return new SingleValueCondition(ConditionType.GE, value)
}
```
In these condition helpers, a more precise type to use would be `Field`. Indeed, generally, the comparison is done on a a reference to a column or a more complex expression based on references or constants.
This improvement in the typescript library will certainly involve a modification of the backend, as well as the Java API.

**Comment by paulbares** [comment]
Hi @jacques-charnay, 
You are right, since the https://github.com/squashql/squashql/releases/tag/1.2.0 release we could indeed improve the api.

**Comment by paulbares** [comment]
A different approach has been taken: see https://github.com/squashql/squashql/pull/206
