### ISSUE TITLE
Expose most of typescript API classes and fields

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#196]
To perform analysis on the table fields used by SquashQL measures and criteria, in order to optimize sub-queries, it is useful for Mercio to access the internal data structure of the typescript SquashQL API. Currently, not all classes are exported, and some have private fields, which makes analysis more complex. (we are forced to use typescript hacks)
Ideally, to facilitate this analysis, the SquashQL API should expose most of its classes and make most of their fields public.

As an illustration, the following measure classes are currently not exposed:

```
class LongConstantMeasure implements Measure {
  readonly class: string = PACKAGE + "LongConstantMeasure"
  readonly alias: string

  constructor(private value: Number) {
  }

  toJSON() {
    return {
      "@class": this.class,
      "value": this.value,
    }
  }
}

class DoubleConstantMeasure implements Measure {
  readonly class: string = PACKAGE + "DoubleConstantMeasure"
  readonly alias: string

  constructor(private value: Number) {
  }

  toJSON() {
    return {
      "@class": this.class,
      "value": this.value,
    }
  }
}
```

Other classes are exposed but keep some of their fields private:

```
export class Criteria {

  constructor(public field: Field,
              public fieldOther: Field,
              private measure: BasicMeasure,
              private condition: Condition,
              public conditionType: ConditionType,
              public children: Criteria[]) {
  }
}
```

**Comment by paulbares** [comment]
I will do it ASAP as I realize it when developing my own UI

**Comment by paulbares** [comment]
I think everything is exposed now. If anything is missing, please open an issue.
