### ISSUE TITLE
More user-friendly execute queries API

### ISSUE THREAD

**Issue by astragier** [squashql/squashql#202]
For now, SquashQL is exposing the following to execute queries with the ts lib:
```
  async execute(query: Query, pivotConfig?: PivotConfig, stringify = false): Promise<QueryResult | PivotTableQueryResult | string>;

  async executeQueryMerge(query: QueryMerge): Promise<QueryResult>;
```

When using it, there are the following pain points:
- having the execution of "simple" queries and drilling accross queries separated add a lot of ifs then else in the code logic,
- having the "simple" queries and the pivot queries handled in the same call makes us systematically cast the result after the call (`as QueryResult` for simple query and `as PivotQueryResult` for pivot ones).

So the proposal is to have the following api:
```
  async executeQuery(query: Query | QueryMerge, stringify = false): Promise<QueryResult>;

  async executePivotQueryMerge(query: Query | QueryMerge, pivotConfig: PivotConfig, stringify = false): Promise<PivotTableQueryResult>;
```

**Comment by paulbares** [comment]
Good idea !

**Comment by astragier** [comment]
Indeed !

**Comment by paulbares** [comment]
It has been done as part of #208
