### ISSUE TITLE
Allow query merge whatever the number of queries

### ISSUE THREAD

**Issue by astragier** [squashql/squashql#203]
Currently we can merge only two queries which is a big limitation.

The method [MergeTables#mergeTables](https://github.com/squashql/squashql/blob/main/core/src/main/java/io/squashql/table/MergeTables.java#L25) already authorize the merge of a list of tables.

It would be great that the ts lib authorize to execute a list of queries and handle the drilling accross among them.
`async executeQueries(queries: Query[], stringify = false): Promise<QueryResult>;`

**Comment by paulbares** [comment]
Added by #248  in the experimental API.

**Comment by paulbares** [comment]
Fixes by #252
