### ISSUE TITLE
Add methods to get TableField dependencies of API objects

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#205]
To optimize SquashQL query building in client code, it is useful to be able to know the `TableField` dependencies of several SquashQL API objects. We mainly need methods to compute the dependencies of:
- `Field`
- `ColumnSet`
- `Measure`
- `Condition`
- `Criteria`

This problem can either be solved in the Java backend or directly in the typescript client. To minimize the number of network calls, and avoid having to write new endpoints, it would be a good idea to implement the dependency search logic directly in the Typescript client.

**Comment by paulbares** [comment]
Fixed by #207
