### ISSUE TITLE
Check if TypedField#name() can be removed

### ISSUE THREAD

**Issue by paulbares** [squashql/squashql#228]

**Comment by mdellabani** [comment]
Removing `TypedField#name()` could be possible. It's used for the following use cases:

- Data loading and schema creation (this can easily be resolved by creating a dedicated pojo for this purpose)
- Aliasing vectors during prefetch (can be removed by using a dedicated internal alias)
- Generating SQL for function and table field (we can keep the name only in these two)
- Experimental QueryMerge feature (we could use aliased field as well I think)

What do you think ?

**Comment by paulbares** [comment]
@mdellabani I removed little by little the usage of Field#name() and TypedField#name() as I discover some issue with its usage. See for instance #260.

https://github.com/squashql/squashql/blob/main/core/src/main/java/io/squashql/query/database/SqlUtils.java#L43

I also added the same method for `Field` (https://github.com/squashql/squashql/blob/main/core/src/main/java/io/squashql/query/database/SqlUtils.java#L57):
```java
  public static String squashqlExpression(Field f) {
    if (f.alias() != null) {
      return f.alias();
    }

    if (f instanceof TableField tf) {
      return getFieldFullName(tf.tableName, tf.fieldName);
    } else if (f instanceof FunctionField ftf) {
      return singleOperandFunctionName(ftf.function, squashqlExpression(f));
    } else {
      throw new IllegalArgumentException(f.getClass().getName());
    }
  }
```
