### ISSUE TITLE
PostgreSQL connector

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#229]
PostgreSQL is a popular database and it would be great to have a connector to use SquashQL with it.

This would be particularly useful for my company, as we have chosen to centralize all data in a postgres DB for the local dev. Currently, we're obliged to make our SquashQL queries via a DuckDB, which acts as a bridge. It works, but it's an awfully slow solution and a pain to maintain.

**Comment by paulbares** [comment]
This is not needed anymore.

**Comment by jacques-charnay** [comment]
> This is not needed anymore.

In my company, a PostgreSQL connector for SquashQL would still be very useful.

![image](https://github.com/squashql/squashql/assets/79094146/b7c1eb9d-7717-4df2-b023-e425016bd1b3)
