### ISSUE TITLE
Support order by measures with QueryJoin

### ISSUE THREAD

**Issue by jacques-charnay** [squashql/squashql#257]
When we try to sort a QueryJoin by a simple SquashQL aggregation measure, then we get an error of this kind in the logs of the SquashQL server:
```
java.lang.RuntimeException: Cannot resolve TableField(tableName=null, fieldName=turnover_initial_sum, fullName=turnover_initial_sum, alias=null)
```
As this sorting by measure is supported in QueryMerge, it would be nice to support it also in QueryJoin.

**Comment by paulbares** [comment]
Hi @jacques-charnay , it is now supported by #280. Note that you have to use `new AliasedField("turnover_initial_sum")` and not `new TableField("turnover_initial_sum")` in the orderBy. TableField is meant to indicate a field belonging to a table in the DB.
