### ISSUE TITLE
Remove the NULLS FIRST

### ISSUE THREAD

**Issue by mathieusanchez** [squashql/squashql#339]
# Issue
To have the totals at the top, `NULLS FIRST` have been added to all the queries.
In my case, when I order on my measure, I have more than 10k lines and more than 10k lines with NULL value on the measure.
So ordering in ASC or DESC only returns NULL values on my measures.

Is this `NULLS FIRST` really useful ?
Could we remove it ?

**Comment by paulbares** [comment]
Hi @mathieusanchez , do you really want to see the null values ? If no, can't you filter out those values ? If yes, a better solution would be to let the user decide via the api if the null values should be put "first" or "last". 
What do you think?

**Comment by mathieusanchez** [comment]
Hi @paulbares, in my use case, I need to keep the null values, because other column and measure could have values too.
I think your second solution is the best.
But I would see this a bit different, the user, thought the API would need to specify if he wants nulls first or last, and if nothing is specified, we let the database handle it.

**Comment by paulbares** [comment]
Actually, the philosophy of squashql is to always return the same result whatever db is used. Letting the db handle it might break this idea because the default behavior of some of them could be to return null first and null last for others.

**Comment by mathieusanchez** [comment]
In that case, if you want to always return the same result, I propose to set `nulls first` for ascending order and `nulls last` for descending order, what do you think ?

**Comment by CooolGeorges** [comment]
The SquashQL default should be null first as group / roll up returns totals as nulls ( not ideal but this is how SQL works ). The client should be able to override this behaviour in the query. In most cases the user does not need to specify it because the hard coded view "knows" that the nulls are not totals. So the change should enable the query to specify null or null last and it will be up the application designer to decide if a UI widget is needed to be exposed to the human

**Comment by paulbares** [comment]
> Actually, the philosophy of squashql is to always return the same result whatever db is used. Letting the db handle it might break this idea because the default behavior of some of them could be to return null first and null last for others.

IMO, it's a bit convoluted. It would be better and clearer to enrich the API to be able to choose null first or null last. If nothing is specified, null first is used by default.
